# Generated by Django 5.1.1 on 2024-10-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('friendliness', models.IntegerField()),
                ('trainability', models.IntegerField()),
                ('sheddingamount', models.IntegerField()),
                ('exerciseneeds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('favorite_food', models.CharField(max_length=50)),
                ('favoritetoys', models.CharField(max_length=50)),
            ],
        ),
    ]
